server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: spiusr
    password: 123123
    url: jdbc:mysql://121.199.32.101/spi?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
sa-token:
  jwt-secret-key: thisIsASecretForThieProjectINeedItBeLongerAndLonger

